### PR TITLE
Implement `AutoTranscriber` class

### PR DESCRIPTION
**Pull request by laubonghaudoi**
1. AutoTranscribe has a higher GPU utilization than the onnx exported one
2. Added more regex rules to the corrector

### CODE REVIEW

**Comment by indiejoseph** [comment]
cannot see CUDA in `Available ONNX providers: ['AzureExecutionProvider', 'CPUExecutionProvider']` on my 3090 PC, I checked `nvidia-smi` my configuration is correct

**Comment by laubonghaudoi** [comment]
呢個係我PR嘅問題定係你合併咗嘅 https://github.com/hon9kon9ize/yuesub-api/pull/6 嘅問題？好似同我嘅PR無關

**Comment by indiejoseph** [comment]
你意思 check available provider 唔出 CUDA, 係因為 #6 ?

**Comment by indiejoseph** [comment]
所以係要 detect GPU 之後再調用 AutoTranscriber

**Comment by indiejoseph** [comment]
如果用 AutoModel 可以唔需要 download onnx models, 由 Funasr 管理 models, 而且需要移走啲唔要嘅 deps 喺 requirements.txt

**Comment by laubonghaudoi** [comment]
係，但係如果萬一要用到原先嘅onnx噉都係保留返好啲？反正保留冇壞處

**Pull request merged**
